experiment_name: 1d_sample

data: SampleData1d
data_args:
  n_threshold: 5
  threshold_length: 5

model_args:
  dimsin: 2
  hidden_nodes: [15, 30]
  dimsout: 1
  loss_function: MSELoss
  optimizer_function: Adam
  lr: 1e-4                           
  wd: 1e-5                 
  epochs: 1                          
  scoring_heuristic: norm_heuristic  