experiment_name: 2d_sample

data: SampleData2d                     
data_args:
  h: 3
  w: 3
  decision_boundary_t: diagonal

model_args:
  dimsin: 2
  hidden_nodes: [15, 30]
  dimsout: 1
  loss_function: MSELoss
  optimizer_function: Adam
  lr: 1e-4                           
  wd: 1e-5                 
  epochs: 1                          
  scoring_heuristic: norm_heuristic  