experiment_name: complete_sample        

# data: SampleData1d
# data_args:
#   n_threshold: 5
#   threshold_length: 5

data: SampleData2d                     
data_args:
  h: 3
  w: 3
  decision_boundary_t: diagonal

model_args:
  dimsin: 2
  hidden_nodes: 15
  dimsout: 1
  loss_function: MSELoss
  optimizer_function: Adam
  lr: 1e-4                           
  wd: 1e-5                 
  epochs: 1                          
  scoring_heuristic: norm_heuristic  