experiment_name: earlystop_testing_only_explore

data: SampleData1d
data_args:
  n_threshold: 4
  threshold_length: 5

model_args:
  dimsin: 1
  hidden_nodes: 1000
  dimsout: 1
  loss_function: MSELoss
  optimizer_function: Adam
  lr: 1e-4                    
  wd: 1e-5                 
  epochs: 250000
  scoring_heuristic: norm_heuristic
  early_stop_patience: 750
  early_stop_delta: 1e-8